### ISSUE TITLE
[Enhanacement Proposal] Implement more of the HTML5 client's functionality

### ISSUE THREAD

**Issue by ShadowEO** [os-js/osjs-xpra-application#10]
First off, XDG Menu Support:

I was looking into this while doing my QOL changes but was having some trouble figuring out how to hook the contextmenu items and the items exported by the HTML5 client together. To be honest it was a minor thing on my mind at the time compared to getting it up and running with authentication support, and I admittedly did not attempt to view the menu's properties directly during runtime yet. I also wanted to ask about the possibility of integrating the XDG Menu perhaps not into the client menu itself, but the desktop's applications menu, is there a way to add items to that menu exposed to application developers?

I think this might be the next logical enhancement for this project, at least in my mind, barring either:

- Xpra Proxy Server support
  - This is where the server creates a session, and then hands that session off to the client, currently that functionality does not seem to work (though it does seem to work in the HTML5 client) and may need additional options to be passed to the JavaScript client component. It's quite possible that this functionality **is** working, but we're lacking the functionality to start anything in the connected session, though IIRC it disconnected from the server every time I attempted.
  - This would also allow multiple users to use the same Xpra websocket address, I could see administrators wishing to lock users into a single Xpra endpoint for shell purposes (if X11/Xpra is provided on the shell/server).
- Possibly supporting chromeless windows (like panel windows drawn by the aformentioned matchbox-panel, which doesn't seem to draw right because of the window chrome), if that's even a possible thing.

---

All three of which I would like some comments or feedback on if you have any. Apologies if any of this seems disjointed, trying to articulate these the best I am able.

What do you think? Could this be a thing, and would it be as simple as me creating a global array to store the stitched together entries and callbacks in, and have the context menu use that as the menu for that item?

Could it even be possible (in the OS.js Applications Menu's current form) to add them to the main applications menu at time of connection, and is there a possible reference I could look towards to guide me in that endeavor?

**Comment by andersevenrud** [comment]
Sorry for late reply. I've been very busy this weekend.

> I was looking into this while doing my QOL changes but was having some trouble figuring out how to hook the contextmenu items and the items exported by the HTML5 client together

This is not something that is exposed all to well in the public APIs. It is possible to populate the menu in a couple of ways though.

> XDG Menu Support

So, yeah. This is doable. Would probably be appropriate to introduce a new hook though that is designed to fit cases like this better. The ways to do it now kind of revolves around how package discovery etc. works.

> Xpra Proxy Server support

I'll have to look into this. I'm not very familiar with this aspect of Xpra.

> Possibly supporting chromeless windows

This should be doable

---

I assume that you've been looking at my [xpra html5 client library](https://github.com/andersevenrud/xpra-html5-client). Note that osjs-xpra-application uses the legacy version of this library, which does not contain nearly as many features etc. as the rewritten one in TypeScript.

So a refactor or rewrite is in order here.

**Comment by ShadowEO** [comment]
I see, and yes I had been looking at the Xpra HTML5 library, as well as the official Xpra HTML5 client in their repository. 

I can see what I can find about the Xpra Proxy server, it doesn't seem to have much in the way of documentation but the HTML5 clients appear to be able to handle it properly.  Glad to see that chromeless windows could be a possibility, and with XDG menu integration, that would remove the need to run a launcher panel like matchbox-panel on the X11 side of things.

**Comment by andersevenrud** [comment]
Closing this issue as any further improvements will most likely come from upstream client since the codebase is steadily improving. And if the trend continues my fork will pretty much become obsolete :)
