### ISSUE TITLE
Cannot start after installation of xpra-application

### ISSUE THREAD

**Issue by oeway** [os-js/osjs-xpra-application#4]
With the latest boilerplate repo, after adding xpra-application and run `npm run package:discover && npm run build && npm run serve`, in the browser the page keep saying "Loading ...".

**Comment by andersevenrud** [comment]
Adding applications does not change anything in the startup process, so I don't think this application has anything to do with it.

Are you getting any logs in the browser devtools console and from the OS.js server ?

**Comment by oeway** [comment]
Nothing suspicious in the log.

The wired thing is that if I remove the Xpra app, it works again. 

It might related to this issue but I cannot run "npm run serve" and I had to set 'sudo sysctl fs.inotify.max_user_watches=524288'. So it might because the server is in trouble?

**Comment by andersevenrud** [comment]
Sounds like that might be the issue. It's a bit strange that you have to adjust your sysctl preferences though. What distro are you on ?

Also, maybe you're running something else on that machine that uses a lot of open files ?

**Comment by andersevenrud** [comment]
I'm closing this one because I'm fairly confident this is unrelated to this repo. If I'm wrong then feel free to re-open.
